# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HouseScrapping' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HouseScrapping
  
  target 'HouseScrappingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HouseScrappingUITests' do
    # Pods for testing
  end

end
